-- Grupo 3 (clasificación). catp_grupo = 3.
-- catp_cod_grupo guarda el código Ofima, con ceros a la izquierda.
-- VARIOS queda con código 0. Los de la lista quedan habilitados.
-- El resto del grupo 3 de la empresa queda deshabilitado.

SET @id_empresa = 1;

UPDATE productos_categorias
SET catp_habilitada = 0
WHERE catp_grupo = 3
  AND catp_id_empresa = @id_empresa;

UPDATE productos_categorias
SET catp_habilitada = 1,
    catp_cod_grupo = CASE CONVERT(catp_nombre USING utf8mb4)
        WHEN 'VARIOS' THEN '0'
        WHEN 'ESTACIONES TOTALES' THEN '001'
        WHEN 'RECEPTOR GNSS - GPS' THEN '002'
        WHEN 'NIVELES' THEN '003'
        WHEN 'ACCESORIOS ESTA-NIVEL-TEO-GNSS' THEN '004'
        WHEN 'GEORRADARES' THEN '005'
        WHEN 'LIDAR SLAM ESCANER' THEN '006'
        WHEN 'COLECTORES Y TABLETS' THEN '007'
        WHEN 'BATERIAS Y CARGADORES TOPOGRAFIA' THEN '008'
        WHEN 'DRONES' THEN '009'
        WHEN 'ACCESORIOS DRONES' THEN '010'
        WHEN 'BATERÍAS Y CARGADORES DRONES' THEN '011'
        WHEN 'REPUESTOS TOPOGRAFIA' THEN '012'
        WHEN 'REPUESTOS GEORRADAR' THEN '013'
        WHEN 'REPUESTOS DRONE AGRAS' THEN '014'
        WHEN 'REPUESTOS DRONE ENTERPRISE' THEN '015'
        WHEN 'REPUESTOS DRONE CONSUMO' THEN '016'
        WHEN 'ESTUCHES Y MORRALES' THEN '017'
        WHEN 'HERRAMIENTAS Y MUEBLES' THEN '018'
        WHEN 'SOFTWARE' THEN '019'
        WHEN 'ENERGIA PORTATIL' THEN '020'
        WHEN 'EQUIPO DE COMPUTO' THEN '021'
        WHEN 'CAMARAS' THEN '022'
        WHEN 'RELOJES' THEN '023'
        WHEN 'AUDIFONOS' THEN '024'
        WHEN 'SERVICIO DE ALQUILER' THEN '025'
        WHEN 'SERVICIO DE CAPACITACION' THEN '026'
        WHEN 'SERVICIO PRO INGENIERIA Y TOPO' THEN '027'
        WHEN 'SERVICIO TECNICO' THEN '028'
        WHEN 'TERMOMETROS' THEN '029'
        WHEN 'TEODOLITOS' THEN '030'
        WHEN 'GENERADORES PLANTA ELECTRICA PORTABLE' THEN '031'
        WHEN 'DISTANCIOMETROS' THEN '032'
        WHEN 'ESCANER LIDAR TERRESTRE' THEN '033'
        WHEN 'LOCALIZADOR DE TUBERIA' THEN '034'
    END
WHERE catp_grupo = 3
  AND catp_id_empresa = @id_empresa
  AND CONVERT(catp_nombre USING utf8mb4) IN (
    'VARIOS',
    'ESTACIONES TOTALES',
    'RECEPTOR GNSS - GPS',
    'NIVELES',
    'ACCESORIOS ESTA-NIVEL-TEO-GNSS',
    'GEORRADARES',
    'LIDAR SLAM ESCANER',
    'COLECTORES Y TABLETS',
    'BATERIAS Y CARGADORES TOPOGRAFIA',
    'DRONES',
    'ACCESORIOS DRONES',
    'BATERÍAS Y CARGADORES DRONES',
    'REPUESTOS TOPOGRAFIA',
    'REPUESTOS GEORRADAR',
    'REPUESTOS DRONE AGRAS',
    'REPUESTOS DRONE ENTERPRISE',
    'REPUESTOS DRONE CONSUMO',
    'ESTUCHES Y MORRALES',
    'HERRAMIENTAS Y MUEBLES',
    'SOFTWARE',
    'ENERGIA PORTATIL',
    'EQUIPO DE COMPUTO',
    'CAMARAS',
    'RELOJES',
    'AUDIFONOS',
    'SERVICIO DE ALQUILER',
    'SERVICIO DE CAPACITACION',
    'SERVICIO PRO INGENIERIA Y TOPO',
    'SERVICIO TECNICO',
    'TERMOMETROS',
    'TEODOLITOS',
    'GENERADORES PLANTA ELECTRICA PORTABLE',
    'DISTANCIOMETROS',
    'ESCANER LIDAR TERRESTRE',
    'LOCALIZADOR DE TUBERIA'
  );

INSERT INTO productos_categorias (catp_nombre, catp_grupo, catp_cod_grupo, catp_habilitada, catp_id_empresa)
SELECT CONVERT(v.nombre USING latin1), 3, v.codigo, 1, @id_empresa
FROM (
    SELECT 'VARIOS' AS nombre, '0' AS codigo
    UNION ALL SELECT 'ESTACIONES TOTALES', '001'
    UNION ALL SELECT 'RECEPTOR GNSS - GPS', '002'
    UNION ALL SELECT 'NIVELES', '003'
    UNION ALL SELECT 'ACCESORIOS ESTA-NIVEL-TEO-GNSS', '004'
    UNION ALL SELECT 'GEORRADARES', '005'
    UNION ALL SELECT 'LIDAR SLAM ESCANER', '006'
    UNION ALL SELECT 'COLECTORES Y TABLETS', '007'
    UNION ALL SELECT 'BATERIAS Y CARGADORES TOPOGRAFIA', '008'
    UNION ALL SELECT 'DRONES', '009'
    UNION ALL SELECT 'ACCESORIOS DRONES', '010'
    UNION ALL SELECT 'BATERÍAS Y CARGADORES DRONES', '011'
    UNION ALL SELECT 'REPUESTOS TOPOGRAFIA', '012'
    UNION ALL SELECT 'REPUESTOS GEORRADAR', '013'
    UNION ALL SELECT 'REPUESTOS DRONE AGRAS', '014'
    UNION ALL SELECT 'REPUESTOS DRONE ENTERPRISE', '015'
    UNION ALL SELECT 'REPUESTOS DRONE CONSUMO', '016'
    UNION ALL SELECT 'ESTUCHES Y MORRALES', '017'
    UNION ALL SELECT 'HERRAMIENTAS Y MUEBLES', '018'
    UNION ALL SELECT 'SOFTWARE', '019'
    UNION ALL SELECT 'ENERGIA PORTATIL', '020'
    UNION ALL SELECT 'EQUIPO DE COMPUTO', '021'
    UNION ALL SELECT 'CAMARAS', '022'
    UNION ALL SELECT 'RELOJES', '023'
    UNION ALL SELECT 'AUDIFONOS', '024'
    UNION ALL SELECT 'SERVICIO DE ALQUILER', '025'
    UNION ALL SELECT 'SERVICIO DE CAPACITACION', '026'
    UNION ALL SELECT 'SERVICIO PRO INGENIERIA Y TOPO', '027'
    UNION ALL SELECT 'SERVICIO TECNICO', '028'
    UNION ALL SELECT 'TERMOMETROS', '029'
    UNION ALL SELECT 'TEODOLITOS', '030'
    UNION ALL SELECT 'GENERADORES PLANTA ELECTRICA PORTABLE', '031'
    UNION ALL SELECT 'DISTANCIOMETROS', '032'
    UNION ALL SELECT 'ESCANER LIDAR TERRESTRE', '033'
    UNION ALL SELECT 'LOCALIZADOR DE TUBERIA', '034'
) v
WHERE NOT EXISTS (
    SELECT 1
    FROM productos_categorias c
    WHERE c.catp_grupo = 3
      AND c.catp_id_empresa = @id_empresa
      AND c.catp_nombre = CONVERT(v.nombre USING latin1)
);
