-- Grupo 2 (sublínea). catp_grupo sigue siendo 2.
-- catp_cod_grupo guarda el código Ofima.
-- Los de la lista quedan habilitados. El resto del grupo 2 de la empresa queda deshabilitado.

SET @id_empresa = 1;

UPDATE productos_categorias
SET catp_habilitada = 0
WHERE catp_grupo = 2
  AND catp_id_empresa = @id_empresa;

UPDATE productos_categorias
SET catp_habilitada = 1,
    catp_cod_grupo = CASE CONVERT(catp_nombre USING utf8mb4)
        WHEN 'VARIOS' THEN '0'
        WHEN 'EQUIPOS AGRICULTURA' THEN '101'
        WHEN 'REPUESTOS DE AGRICULTURA' THEN '102'
        WHEN 'ACCESORIOS DE AGRICULTURA' THEN '103'
        WHEN 'SOFTWARE DE AGRICULTURA' THEN '104'
        WHEN 'HERRAMIENTAS DE AGRICULTURA' THEN '105'
        WHEN 'EQUIPOS TOPOGRAFÍA' THEN '201'
        WHEN 'REPUESTOS DE TOPOGRAFÍA' THEN '202'
        WHEN 'ACCESORIOS TOPOGRAFÍA' THEN '203'
        WHEN 'SOFTWARE TOPOGRAFÍA' THEN '204'
        WHEN 'HERRAMIENTAS DE TOPOGRAFÍA' THEN '205'
        WHEN 'DRONES ENTERPRISE' THEN '206'
        WHEN 'DRONES TOPOGRAFÍA' THEN '207'
        WHEN 'CURSOS Y CAPACITACIONES' THEN '301'
        WHEN 'SERVICIO TÉCNICO AGRICULTURA' THEN '302'
        WHEN 'SERVICIOS DE INGENIERIA Y TOPOGRAFÍA' THEN '303'
        WHEN 'SERVICIO TECNICO DE TOPOGRAFÍA' THEN '304'
        WHEN 'SERVICIO TÉCNICO TOPOGRAFÍA Y GPR' THEN '305'
        WHEN 'DRONES CONSUMO' THEN '401'
        WHEN 'GADGETS' THEN '402'
        WHEN 'REPUESTOS CONSUMO' THEN '403'
    END
WHERE catp_grupo = 2
  AND catp_id_empresa = @id_empresa
  AND CONVERT(catp_nombre USING utf8mb4) IN (
    'VARIOS',
    'EQUIPOS AGRICULTURA',
    'REPUESTOS DE AGRICULTURA',
    'ACCESORIOS DE AGRICULTURA',
    'SOFTWARE DE AGRICULTURA',
    'HERRAMIENTAS DE AGRICULTURA',
    'EQUIPOS TOPOGRAFÍA',
    'REPUESTOS DE TOPOGRAFÍA',
    'ACCESORIOS TOPOGRAFÍA',
    'SOFTWARE TOPOGRAFÍA',
    'HERRAMIENTAS DE TOPOGRAFÍA',
    'DRONES ENTERPRISE',
    'DRONES TOPOGRAFÍA',
    'CURSOS Y CAPACITACIONES',
    'SERVICIO TÉCNICO AGRICULTURA',
    'SERVICIOS DE INGENIERIA Y TOPOGRAFÍA',
    'SERVICIO TECNICO DE TOPOGRAFÍA',
    'SERVICIO TÉCNICO TOPOGRAFÍA Y GPR',
    'DRONES CONSUMO',
    'GADGETS',
    'REPUESTOS CONSUMO'
  );

INSERT INTO productos_categorias (catp_nombre, catp_grupo, catp_cod_grupo, catp_habilitada, catp_id_empresa)
SELECT CONVERT(v.nombre USING latin1), 2, v.codigo, 1, @id_empresa
FROM (
    SELECT 'VARIOS' AS nombre, '0' AS codigo
    UNION ALL SELECT 'EQUIPOS AGRICULTURA', '101'
    UNION ALL SELECT 'REPUESTOS DE AGRICULTURA', '102'
    UNION ALL SELECT 'ACCESORIOS DE AGRICULTURA', '103'
    UNION ALL SELECT 'SOFTWARE DE AGRICULTURA', '104'
    UNION ALL SELECT 'HERRAMIENTAS DE AGRICULTURA', '105'
    UNION ALL SELECT 'EQUIPOS TOPOGRAFÍA', '201'
    UNION ALL SELECT 'REPUESTOS DE TOPOGRAFÍA', '202'
    UNION ALL SELECT 'ACCESORIOS TOPOGRAFÍA', '203'
    UNION ALL SELECT 'SOFTWARE TOPOGRAFÍA', '204'
    UNION ALL SELECT 'HERRAMIENTAS DE TOPOGRAFÍA', '205'
    UNION ALL SELECT 'DRONES ENTERPRISE', '206'
    UNION ALL SELECT 'DRONES TOPOGRAFÍA', '207'
    UNION ALL SELECT 'CURSOS Y CAPACITACIONES', '301'
    UNION ALL SELECT 'SERVICIO TÉCNICO AGRICULTURA', '302'
    UNION ALL SELECT 'SERVICIOS DE INGENIERIA Y TOPOGRAFÍA', '303'
    UNION ALL SELECT 'SERVICIO TECNICO DE TOPOGRAFÍA', '304'
    UNION ALL SELECT 'SERVICIO TÉCNICO TOPOGRAFÍA Y GPR', '305'
    UNION ALL SELECT 'DRONES CONSUMO', '401'
    UNION ALL SELECT 'GADGETS', '402'
    UNION ALL SELECT 'REPUESTOS CONSUMO', '403'
) v
WHERE NOT EXISTS (
    SELECT 1
    FROM productos_categorias c
    WHERE c.catp_grupo = 2
      AND c.catp_id_empresa = @id_empresa
      AND c.catp_nombre = CONVERT(v.nombre USING latin1)
);
